### PR TITLE
Bring the statistics page back to a working state

### PR DESCRIPTION
**Pull request by jwshields**
Small changes here-
Mostly, the statistics page was not working at all for me.
I got the table to start drawing, but was unable to get the chart to show up. (Some googling around shows you need to allow unsafe-eval in the CSP.)
- The json of the options is showing as invalid when you load the statistics page, unsure really how to fix it. I enabled unsafe eval in the manifest to test, but it did not appear to change much for me, but I'm not a JS developer

I also removed some links to the old Google Extension page for BetterHistory & references to the hijacked fork.

### CODE REVIEW

**Comment by jwshields** [comment]
Hello!
I merged your edit into my branch to resolve the conflict; worded much better

**Comment by akatrevorjay** [comment]
You're the best!

**Comment by akatrevorjay** [comment]
Ok, the issue with the google API is that I removed that on purpose. I'd much rather it use a local graphing library instead of a googley one, which is why I just broke the page. Lol.

**Comment by akatrevorjay** [comment]
@jwshields BSD is compatible to use as a library into GPL, the issue is the other way around afaik, hence LGPL.

**Pull request closed without merging**
